sudo: required
services:
  - docker

before_install:
  - docker build -t bmshamsnahid/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test -- --coverage

after_success:
  - docker build -t bmshamsnahid/multi-client ./client
  - docker build -t bmshamsnahid/multi-nginx ./nginx
  - docker build -t bmshamsnahid/multi-server ./server
  - docker build -t bmshamsnahid/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bmshamsnahid/multi-client
  - docker push bmshamsnahid/multi-nginx
  - docker push bmshamsnahid/multi-server
  - docker push bmshamsnahid/multi-worker